packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  '@nuxt/eslint': ^1.15.2
  '@nuxtjs/i18n': ^10.2.4
  '@nuxtjs/seo': ^5.1.2
  '@pinia/nuxt': ^0.11.3
  '@tanstack/form-core': ^1.29.1
  '@tanstack/vue-form': ^1.29.1
  '@ark-ui/vue': ^5.36.2
  '@nuxt/kit': ^4.4.2
  '@tailwindcss/vite': ^4.2.2
  '@types/minimist': ^1.2.5
  '@types/node': ^25.5.2
  '@vite-pwa/nuxt': ^1.1.1
  '@vueuse/nuxt': ^14.2.1
  class-variance-authority: ^0.7.1
  nuxt-security: ^2.5.1
  tailwind-merge: ^3.5.0
  'vue-router': ^5.0.4
  'vue': ^3.5.32
  'yaml': ^2.8.1
  eslint: ^10.2.0
  nuxt: ^4.4.2
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  typescript: ^6.0.2
  vitest: ^3.2.4
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  zod: ^4.3.6
  vue-tsc: ^2.2.12
  '@playwright/test': ^1.59.1
  playwright: ^1.59.1

minimumReleaseAge: 1440 # 24 hours
