packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  '@tanstack/vue-form': ^1.29.1
  '@ark-ui/vue': ^5.36.2
  '@nuxt/kit': ^4.4.2
  '@tailwindcss/vite': ^4.2.2
  '@types/minimist': ^1.2.5
  '@types/node': ^25.5.2
  class-variance-authority: ^0.7.1
  'vue-router': ^5.0.4
  'vue': ^3.5.32
  'yaml': ^2.8.1
  eslint: ^10.2.0
  nuxt: ^4.4.2
  oxfmt: ^0.44.0
  oxlint: ^1.59.0
  typescript: ^6.0.2
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  zod: ^4.3.6

minimumReleaseAge: 1440 # 24 hours
