packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  '@types/minimist': ^1.2.5
  '@types/node': ^25.5.2
  typescript: ^6.0.2
  eslint: ^10.2.0
  oxfmt: ^0.44.0
  oxlint: ^1.59.0

minimumReleaseAge: 1440 # 24 hours
