/**
 * GENERATED by `scripts/gen-tokens.ts` — do not edit.
 *
 * Which role tokens read each palette stop, per theme. `dark` is not a mirror of
 * `light`: text and border roles are pitched differently so both themes clear their
 * WCAG floors against the same eleven stops.
 */

export const ROLE_INDEX = {
  dark: {
    50: ['text'],
    100: ['bg-inverse', 'on-fill', 'on-fill-subtle'],
    200: ['border-strong-active', 'surface-inverse'],
    300: ['border-strong-hover', 'icon', 'text-subtle'],
    400: ['border', 'border-strong', 'fill-active', 'fill-inverse', 'icon-subtle', 'text-muted'],
    500: ['border-inverse', 'border-subtle-active', 'fill-hover', 'fill-subtle-active'],
    600: ['border-active', 'border-subtle-hover', 'fill', 'fill-subtle-hover'],
    700: ['border-hover', 'fill-subtle', 'icon-disabled', 'text-disabled'],
    800: ['border-subtle', 'icon-inverse', 'surface'],
    900: ['bg', 'surface-subtle', 'text-inverse'],
    950: ['bg-subtle'],
  },
  light: {
    50: ['bg-subtle'],
    100: ['bg', 'on-fill', 'surface-subtle', 'text-inverse'],
    200: ['icon-inverse', 'surface'],
    300: ['border-inverse', 'fill-subtle', 'icon-disabled', 'text-disabled'],
    400: ['border-subtle', 'border-subtle-hover', 'fill-inverse', 'fill-subtle-hover'],
    500: [
      'border-hover',
      'border-subtle-active',
      'fill-subtle-active',
      'icon-subtle',
      'text-muted',
    ],
    600: ['border-active', 'fill', 'text-subtle'],
    700: ['border', 'fill-hover', 'icon'],
    800: ['border-strong', 'fill-active', 'surface-inverse'],
    900: ['bg-inverse', 'border-strong-hover', 'on-fill-subtle', 'text'],
    950: ['border-strong-active'],
  },
} as const satisfies Record<'dark' | 'light', Record<number, readonly string[]>>

export type RoleIndexTheme = keyof typeof ROLE_INDEX
